name: FantasticSpawn
main: com.iamforyydev.FantasticSpawn
version: 1.1
author: iAmForyyDev_
softdepend: [PlaceholderAPI]

commands:
  fantasticspawn:
    aliases: [fspawn]
    description: main command